name: shimmer_animation
description: This shimmer animation widget can help you bring simple yet beautiful skeleton loaders to your project with ease.
version: 2.2.1
#author: maddyb99 <maddybcorp@outlook.com>
homepage: https://github.com/maddyb99/shimmer_animation

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
